/*标题汉化*/
insert or replace into EnglishText
	(Tag,										Text)
values
	('LOC_9729f5372fd44449a854574becb8ccaa',	'LOC_MTL_TEMPLE_OF_SOLOMON_NAME'),
	('LOC_437690d48c574f30bc958cb7143fad81',	'LOC_MTL_BASTROD_AMAZON_THEATRE_NAME'),
	('LOC_af3b9ab9c2e64a4db6bc2797144b9b05',	'LOC_MTL_PHANTA_WORLD_TRADE_CENTER_MOD_NAME'),
	('LOC_10c534a7c6b740a9a38ee978a5c42887',	'LOC_MTL_PHANTA_GREAT_SPHINX_MOD_NAME'),
	('LOC_e75e56231a4a4a7b9fe7b4d8a796c5be',	'LOC_MTL_HARMANDIR_SAHIB_NAME'),
	('LOC_665955444f5a4e768831ec32b08ce100',	'LOC_MTL_ATACAMA_GIANT_NAME'),
	('LOC_4237d034980c47baa00395720ad52988',	'LOC_MTL_TORRE_DEL_ORO_NAME'),
	('LOC_084cef748ccf44378e4cbca7a306907f',	'LOC_MTL_PHANTA_NAGOYA_CASTLE_MOD_NAME'),
	('LOC_597b19d7b7594b9c8cf1b0ac3358010a',	'LOC_MTL_WONDER_LOULAN_NAME'),
	('LOC_7b26e85f6bb742b88c2dc3302b95952c',	'LOC_MTL_PHANTA_SANXINGDUI_MOD_NAME'),
	('LOC_bc43037570184df7a2a7994669d8edd3',	'LOC_MTL_PYRAMID_OF_THE_SUN_AND_MOON_NAME'),
	('LOC_5d3a19ecd7a24ace8c76cba8c7981f4c',	'LOC_MTL_PHANTA_PAVILION_PRINCE_TENG_MOD_NAME'),
	('LOC_50dcb53f91c0496b950f821e29fd14bc',	'LOC_MTL_PARTHENON_NAME'),
	('LOC_09dc6701148e4504b0475775dee07806',	'LOC_MTL_PHANTA_OSAKA_CASTLE_MOD_NAME'),
	('LOC_1b8e4be673ae4827acf59d5b1de31487',	'LOC_MTL_ORIENTAL_PEARL_TOWER_MOD_NAME'),
	('LOC_835737cef4934e0bb4365a01c82abd63',	'LOC_MTL_OLD_ELIZABETHAN_LONDON_BRIDGE_NAME'),
	('LOC_19945369479244659b9a6763d75017e7',	'LOC_MTL_PHANTA_NOTRE_DAME_SAIGON_MOD_NAME'),
	('LOC_77155097b1f948baabae10c026365c99',	'LOC_MTL_GLOBAL_SEED_VAULT_NAME'),
	('LOC_43e4ac684ce44e6a8ecafbe81fdbd1df',	'LOC_MTL_PHANTA_BRONZE_BIRD_TERRACE_MOD_NAME'),
	('LOC_84335908588245c1aea2f87ab4f3b52c',	'LOC_MTL_BUKHARA_NAME'),
	('LOC_e8ed563719074bdc8acd2e2ab4477221',	'LOC_MTL_PHANTA_FUSHIMI_INARI_TAISHA_MOD_NAME'),
	('LOC_e43a33492e104221bbe749053dccb698',	'LOC_MTL_CATHEDRAL_CHRIST_SAVIOUR_NAME'),
	('LOC_ba2728be1c9d41668b19f92f9dfb6128',	'LOC_MTL_DOME_OF_THE_ROCK_NAME'),
	('LOC_0f63b57f409640f08f575618ef1e3cff',	'LOC_MTL_SANTA_MARIA_DEL_FIORE_NAME'),
	('LOC_69b006ce837e40c9a57e1249a22770a2',	'LOC_MTL_PHANTA_LEIFENG_MOD_NAME'),
	('LOC_c9d2515521b047199ab4a192d1808149',	'LOC_MTL_TITANIC_WONDER_NAME'),
	('LOC_80e4eb638e8a43ecb07e25751f08a4d0',	'LOC_MTL_ARAKURA_FUJI_SENGEN_SHRINE_NAME'),
	('LOC_70c6f581a60946ab90f704c9f961ec53',	'LOC_MTL_TAQ_KASRA_NAME');
--	('LOC_da699ee4ba644441992c94a326c02a34',	'LOC_MTL_BUILDING_MC_LEFKOS_PYRGOS_NAME');

insert or replace into LocalizedText
	(Language,		Tag,													Text)
values
	('en_US',		'LOC_MTL_TEMPLE_OF_SOLOMON_NAME',					'[World Wonder]Temple of Solomon'),
	('zh_Hans_CN',	'LOC_MTL_TEMPLE_OF_SOLOMON_NAME',					'[世界奇观]所罗门圣殿'),
	('en_US',		'LOC_MTL_BASTROD_AMAZON_THEATRE_NAME',				'[World Wonder]Amazon Theatre'),
	('zh_Hans_CN',	'LOC_MTL_BASTROD_AMAZON_THEATRE_NAME',				'[世界奇观]亚马逊剧院'),
	('en_US',		'LOC_MTL_PHANTA_WORLD_TRADE_CENTER_MOD_NAME',		'[World Wonder]World Trade Center'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_WORLD_TRADE_CENTER_MOD_NAME',		'[世界奇观]世界贸易中心'),
	('en_US',		'LOC_MTL_PHANTA_GREAT_SPHINX_MOD_NAME',				'[World Wonder]Great Sphinx of Giza'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_GREAT_SPHINX_MOD_NAME',				'[世界奇观]吉萨狮身人面像'),
	('en_US',		'LOC_MTL_HARMANDIR_SAHIB_NAME',						'[World Wonder]Harmandir Sahib'),
	('zh_Hans_CN',	'LOC_MTL_HARMANDIR_SAHIB_NAME',						'[世界奇观]阿姆利则金庙'),
	('en_US',		'LOC_MTL_ATACAMA_GIANT_NAME',						'[World Wonder]Atacama Geoglyph'),
	('zh_Hans_CN',	'LOC_MTL_ATACAMA_GIANT_NAME',						'[世界奇观]阿塔卡马地画'),
	('en_US',		'LOC_MTL_TORRE_DEL_ORO_NAME',						'[World Wonder]Torre del Oro'),
	('zh_Hans_CN',	'LOC_MTL_TORRE_DEL_ORO_NAME',						'[世界奇观]黄金塔'),
	('en_US',		'LOC_MTL_PHANTA_NAGOYA_CASTLE_MOD_NAME',			'[World Wonder]Nagoya Castle'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_NAGOYA_CASTLE_MOD_NAME',			'[世界奇观]名古屋城'),
	('en_US',		'LOC_MTL_WONDER_LOULAN_NAME',						'[World Wonder]Lou Lan'),
	('zh_Hans_CN',	'LOC_MTL_WONDER_LOULAN_NAME',						'[世界奇观]楼兰城'),
	('en_US',		'LOC_MTL_PHANTA_SANXINGDUI_MOD_NAME',				'[World Wonder]Sanxingdui'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_SANXINGDUI_MOD_NAME',				'[世界奇观]三星堆'),
	('en_US',		'LOC_MTL_PYRAMID_OF_THE_SUN_AND_MOON_NAME',			'[World Wonder]Pyramid of the Sun and Moon'),
	('zh_Hans_CN',	'LOC_MTL_PYRAMID_OF_THE_SUN_AND_MOON_NAME',			'[世界奇观]太阳/月亮金字塔'),
	('en_US',		'LOC_MTL_PHANTA_PAVILION_PRINCE_TENG_MOD_NAME',		'[World Wonder]Pavilion of Prince Teng'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_PAVILION_PRINCE_TENG_MOD_NAME',		'[世界奇观]滕王阁'),
	('en_US',		'LOC_MTL_PARTHENON_NAME',							'[World Wonder]Parthenon'),
	('zh_Hans_CN',	'LOC_MTL_PARTHENON_NAME',							'[世界奇观]帕特农神庙'),
	('en_US',		'LOC_MTL_PHANTA_OSAKA_CASTLE_MOD_NAME',				'[World Wonder]Osaka Castle'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_OSAKA_CASTLE_MOD_NAME',				'[世界奇观]大坂城'),
	('en_US',		'LOC_MTL_ORIENTAL_PEARL_TOWER_MOD_NAME',			'[World Wonder]Oriental Pearl Tower'),
	('zh_Hans_CN',	'LOC_MTL_ORIENTAL_PEARL_TOWER_MOD_NAME',			'[世界奇观]东方明珠电视塔'),
	('en_US',		'LOC_MTL_OLD_ELIZABETHAN_LONDON_BRIDGE_NAME',		'[World Wonder]Old Elizabethan London Bridge'),
	('zh_Hans_CN',	'LOC_MTL_OLD_ELIZABETHAN_LONDON_BRIDGE_NAME',		'[世界奇观]旧伦敦桥'),
	('en_US',		'LOC_MTL_PHANTA_NOTRE_DAME_SAIGON_MOD_NAME',		'[World Wonder]Notre-Dame Cathedral of Saigon'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_NOTRE_DAME_SAIGON_MOD_NAME',		'[世界奇观]西贡圣母大教堂'),
	('en_US',		'LOC_MTL_GLOBAL_SEED_VAULT_NAME',					'[World Wonder]Svalbard Global Seed Vault'),
	('zh_Hans_CN',	'LOC_MTL_GLOBAL_SEED_VAULT_NAME',					'[世界奇观]斯瓦尔巴群岛全球种子库'),
	('en_US',		'LOC_MTL_PHANTA_BRONZE_BIRD_TERRACE_MOD_NAME',		'[World Wonder]Bronze Bird Terrace'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_BRONZE_BIRD_TERRACE_MOD_NAME',		'[世界奇观]铜雀台'),
	('en_US',		'LOC_MTL_BUKHARA_NAME',								'[World Wonder]Bukhara'),
	('zh_Hans_CN',	'LOC_MTL_BUKHARA_NAME',								'[世界奇观]布哈拉'),
	('en_US',		'LOC_MTL_PHANTA_FUSHIMI_INARI_TAISHA_MOD_NAME',		'[World Wonder]Fushimi Inari-Taisha'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_FUSHIMI_INARI_TAISHA_MOD_NAME',		'[世界奇观]伏见稻荷大社'),
	('en_US',		'LOC_MTL_CATHEDRAL_CHRIST_SAVIOUR_NAME',			'[World Wonder]Cathedral of Christ the Saviour'),
	('zh_Hans_CN',	'LOC_MTL_CATHEDRAL_CHRIST_SAVIOUR_NAME',			'[世界奇观]基督救世主大教堂'),
	('en_US',		'LOC_MTL_DOME_OF_THE_ROCK_NAME',					'[World Wonder]Dome of the Rock'),
	('zh_Hans_CN',	'LOC_MTL_DOME_OF_THE_ROCK_NAME',					'[世界奇观]岩石圆顶'),
	('en_US',		'LOC_MTL_SANTA_MARIA_DEL_FIORE_NAME',				'[World Wonder]Santa Maria del Fiore'),
	('zh_Hans_CN',	'LOC_MTL_SANTA_MARIA_DEL_FIORE_NAME',				'[世界奇观]圣母百花大教堂'),
	('en_US',		'LOC_MTL_PHANTA_LEIFENG_MOD_NAME',					'[World Wonder]Leifeng Pagoda'),
	('zh_Hans_CN',	'LOC_MTL_PHANTA_LEIFENG_MOD_NAME',					'[世界奇观]雷峰塔'),
	('en_US',		'LOC_MTL_TITANIC_WONDER_NAME',						'[World Wonder]Titanic'),
	('zh_Hans_CN',	'LOC_MTL_TITANIC_WONDER_NAME',						'[世界奇观]泰坦尼克号'),
	('en_US',		'LOC_MTL_ARAKURA_FUJI_SENGEN_SHRINE_NAME',			'[World Wonder]Arakura Fuji Sengen Shrine'),
	('zh_Hans_CN',	'LOC_MTL_ARAKURA_FUJI_SENGEN_SHRINE_NAME',			'[世界奇观]新仓富士浅间神社'),
	('en_US',		'LOC_MTL_TAQ_KASRA_NAME',							'[World Wonder]Taq Kasra'),
	('zh_Hans_CN',	'LOC_MTL_TAQ_KASRA_NAME',							'[世界奇观]塔克基思拉宫');
--	('en_US',		'LOC_MTL_BUILDING_MC_LEFKOS_PYRGOS_NAME',			'[World Wonder]Lefkós Pýrgos'),
--	('zh_Hans_CN',	'LOC_MTL_BUILDING_MC_LEFKOS_PYRGOS_NAME',			'[世界奇观]塞萨洛尼基白塔');
